version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/linked-gold/resource-service
    overwrite: yes

permissions:
  - object: /home/ec2-user/linked-gold/resource-service
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60