name: Deploy Auth Service

on:
  push:
    branches: ["main", "develop"]

env:
  SERVICE_NAME: auth-service
  BUCKET_NAME: linked-gold-bucket
  S3_ZIP_NAME: auth-service.zip
  CODE_DEPLOY_APP_NAME: linked-gold
  DEPLOYMENT_GROUP_NAME: linked-gold-auth-deployment-group

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: 21
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build Auth Service
      run: cd ${{ env.SERVICE_NAME }} && ./gradlew clean build -x test
      
    - name: Zip Auth Service
      run: cd ${{ env.SERVICE_NAME }} && zip -qq -r $GITHUB_WORKSPACE/${{ env.S3_ZIP_NAME }} build/
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp $GITHUB_WORKSPACE/${{ env.S3_ZIP_NAME }} s3://$BUCKET_NAME/$SERVICE_NAME/${{ env.S3_ZIP_NAME }}

    - name: Code Deploy
      run: aws deploy create-deployment --application-name $CODE_DEPLOY_APP_NAME --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name $DEPLOYMENT_GROUP_NAME --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$SERVICE_NAME/${{ env.S3_ZIP_NAME }}
