name: Build and Deploy for WOWMATE server to AWS EC2

on:
  push:
    branches: [ develop ]

env:
  PROJECT_NAME: Linked-Gold_Server
  BUCKET_NAME: linked-gold-bucket
  CODE_DEPLOY_APP_NAME: linked-gold
  DEPLOYMENT_GROUP_NAME: linked-gold-deployment-group

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: 21
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build -x test
      
    - name: Make Zip File
      run: zip -qq -r $GITHUB_WORKSPACE/$GITHUB_SHA.zip .
      shell: bash
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
      
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 $GITHUB_WORKSPACE/$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

    - name: Code Deploy
      run: aws deploy create-deployment --application-name $CODE_DEPLOY_APP_NAME --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name $DEPLOYMENT_GROUP_NAME --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
